AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvironmentName:
    Type: String
    Default: eks-aws-fault-injection-simulator
    Description: Name of EKS blueprint
  NodeImageIdSSMParam:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/eks/optimized-ami/1.22/amazon-linux-2/recommended/image_id
    Description: AWS Systems Manager Parameter Store parameter of the AMI ID for the
      worker node instances. Change this value to match the version of
      Kubernetes you are using.
Resources:
  spotBlueprintsEksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  spotBlueprintsNodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication
      VpcId: vpc-04ddbf841c6d2ea3d
  ControlPlaneSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: ControlPlaneSecurityGroup
      SourceSecurityGroupId:
        Ref: ControlPlaneSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
  AWSEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: eks-aws-fault-injection-simulator
      Version: "1.22"
      RoleArn:
        Fn::GetAtt:
          - spotBlueprintsEksClusterRole
          - Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Ref: ControlPlaneSecurityGroup
        SubnetIds:
          - subnet-026188f49f73e2f93
          - subnet-0927309ec69542f5e
          - subnet-011764cd8b220ac81
          - subnet-07e9ce26b41553f70
          - subnet-07cc99ff7bb34329e
  NodeGroup1:
    Type: AWS::EKS::Nodegroup
    Properties:
      InstanceTypes:
        - c3.large
        - c4.large
        - c5.large
      ScalingConfig:
        MinSize: 2
        MaxSize: 2
        DesiredSize: 2
      ClusterName:
        Ref: AWSEKSCluster
      CapacityType: SPOT
      Subnets:
        - subnet-026188f49f73e2f93
        - subnet-0927309ec69542f5e
        - subnet-011764cd8b220ac81
        - subnet-07e9ce26b41553f70
        - subnet-07cc99ff7bb34329e
      NodeRole:
        Fn::GetAtt:
          - spotBlueprintsNodeInstanceRole
          - Arn
  NodeGroup2:
    Type: AWS::EKS::Nodegroup
    Properties:
      InstanceTypes:
        - m4.large
        - m5.large
        - m3.large
      ScalingConfig:
        MinSize: 2
        MaxSize: 2
        DesiredSize: 2
      ClusterName:
        Ref: AWSEKSCluster
      CapacityType: SPOT
      Subnets:
        - subnet-026188f49f73e2f93
        - subnet-0927309ec69542f5e
        - subnet-011764cd8b220ac81
        - subnet-07e9ce26b41553f70
        - subnet-07cc99ff7bb34329e
      NodeRole:
        Fn::GetAtt:
          - spotBlueprintsNodeInstanceRole
          - Arn
  NodeGroup3:
    Type: AWS::EKS::Nodegroup
    Properties:
      InstanceTypes:
        - r3.large
        - r5.large
        - r4.large
      ScalingConfig:
        MinSize: 2
        MaxSize: 2
        DesiredSize: 2
      ClusterName:
        Ref: AWSEKSCluster
      CapacityType: SPOT
      Subnets:
        - subnet-026188f49f73e2f93
        - subnet-0927309ec69542f5e
        - subnet-011764cd8b220ac81
        - subnet-07e9ce26b41553f70
        - subnet-07cc99ff7bb34329e
      NodeRole:
        Fn::GetAtt:
          - spotBlueprintsNodeInstanceRole
          - Arn
Outputs:
  spotBlueprintsNodeInstanceRole:
    Description: The node instance role
    Value:
      Fn::GetAtt:
        - spotBlueprintsNodeInstanceRole
        - Arn
  ClusterCertificate:
    Description: The cluster certificate
    Value:
      Fn::GetAtt:
        - AWSEKSCluster
        - CertificateAuthorityData
  ClusterEndpoint:
    Description: The cluster endpoint
    Value:
      Fn::GetAtt:
        - AWSEKSCluster
        - Endpoint
